services:
  odoo:
    image: odoo:18
    container_name: odoo
    restart: unless-stopped
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=${RDS_HOST}
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - odoo_network

  nginx:
    image: nginx:alpine
    container_name: odoo_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - odoo
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo_data:
